@startuml
'https://plantuml.com/activity-diagram-beta

start
-> POST <color:blue>/rest/coLine/updateLiability
Request Body:
    + productionOrderNo
    + userId
    + liability;
if (liability is <color:green>"TAP") is (yes) then
  :liabilityToUpdate = "BUYER"
  priceTermToUpdate = "CMT";
else (no)
  :liabilityToUpdate = "TAP"
    priceTermToUpdate = "FOB";
endif

:UPDATE

liability = <color:green>**liabilityToUpdate**
priceTerm = <color:green>**priceTermToUpdate**
salesPrice = liability == "BUYER" ? <color:green>**(FobBasicPrice + UpchargeCost)**</color> : <color:red>**(CmtBasicPrice + UpchargeCost)**</color>

IN **TC_M3_CO_LINE_UPLOAD**;


:UPDATE

liability = <color:green>**liabilityToUpdate**
priceTerm = <color:green>**priceTermToUpdate**
salesPrice = liability == "BUYER" ? <color:green>**(FobBasicPrice + UpchargeCost)**</color> : <color:red>**(CmtBasicPrice + UpchargeCost)**</color>

IN **TC_M3_CO_LINE_MTM_RAW**;



stop

@enduml
